import { GoogleGenAI, Chat } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    console.error("API Key is missing.");
  }
  return new GoogleGenAI({ apiKey: apiKey || 'dummy_key_mock' });
};

// We store the chat session instance to maintain history
let currentChatSession: Chat | null = null;

export const resetChat = () => {
  currentChatSession = null;
};

const getSystemInstruction = () => `
  You are Water IA, an elite Roblox Luau developer and scripter.
  
  MANDATORY RULES:
  1. WATERMARK: Every single Lua script code block you generate MUST start with these exact lines:
     -- [[ Water IA Hub ]] --
     -- [[ Generated by Water IA ]] --
     
  2. CONTEXT: The user might ask you to modify previous code (e.g., "make it a custom GUI", "fix the speed"). You must understand the context and rewrite the script accordingly.
  
  3. VISUALS: If the user asks for a UI/GUI:
     - Default to 'OrionLib', 'Fluent', or 'Rayfield' for quick execution.
     - If the user explicitly asks for "custom GUI" or "make your own GUI", write a custom Instance.new("ScreenGui") script with smooth tweens and rounded corners.
  
  4. COMPATIBILITY: Code must be compatible with Xeno, Solara, Fluxus, Delta.
  
  5. FORMAT: Use markdown code blocks for scripts. You can add brief text explanations outside the code block.
  
  6. LANGUAGE: Speak Portuguese (Brazil).
`;

export const sendMessageToWaterIA = async (message: string): Promise<string> => {
  const ai = getClient();

  if (!currentChatSession) {
    currentChatSession = ai.chats.create({
      model: 'gemini-3-pro-preview',
      config: {
        systemInstruction: getSystemInstruction(),
        temperature: 0.7,
      },
    });
  }

  try {
    const response = await currentChatSession.sendMessage({ message });
    return response.text || "-- Erro: Resposta vazia da IA.";
  } catch (error) {
    console.error("Gemini Chat Error:", error);
    return `Desculpe, ocorreu um erro na conexão com o servidor Water IA.\nErro: ${error instanceof Error ? error.message : "Desconhecido"}`;
  }
};

export const startChatWithScript = async (scriptCode: string, scriptTitle: string): Promise<string> => {
  const ai = getClient();
  
  // Create a fresh session
  currentChatSession = ai.chats.create({
    model: 'gemini-3-pro-preview',
    config: {
      systemInstruction: getSystemInstruction(),
      temperature: 0.7,
    },
  });

  const contextPrompt = `
    O usuário está carregando um script salvo chamado "${scriptTitle}" para continuar editando.
    
    Aqui está o código atual:
    \`\`\`lua
    ${scriptCode}
    \`\`\`
    
    Analise este código e responda confirmando que entendeu. Diga algo como "Carreguei o script [Nome]. O que deseja alterar?".
    NÃO reescreva o código ainda, apenas confirme.
  `;

  try {
    const response = await currentChatSession.sendMessage({ message: contextPrompt });
    return response.text || `Carreguei o script **${scriptTitle}**. O que deseja alterar nele?`;
  } catch (error) {
    console.error("Context Load Error:", error);
    return `Carreguei o script **${scriptTitle}**, mas tive um problema de conexão. Podemos tentar editar mesmo assim.`;
  }
};